<?php

namespace App\Filament\Widgets;

use App\Models\Order;
use App\Models\Type;
use Filament\Widgets\ChartWidget;
use Flowframe\Trend\Trend;
use Illuminate\Contracts\Support\Htmlable;

class OrderStateChart extends ChartWidget
{
    public function getHeading(): string|Htmlable|null
    {
        return trans('ecommerce.widget.state'); // TODO: Change the autogenerated stub
    }

    protected int|string|array $columnSpan = 2;

    protected function getData(): array
    {
        $orderQuery = Order::query();
        $orderStates = Type::query()
            ->where('for', 'orders')
            ->where('type', 'status')
            ->get();
        $trend = Trend::query((clone $orderQuery))
            ->interval('day')
            ->dateColumn('created_at')
            ->between(
                now()->subWeek(),
                now()
            )
            ->count();

        $datasets = [];
        foreach ($orderStates as $item) {
            $datasets[] = [
                'label' => $item->name,
                'data' => Trend::query((clone $orderQuery)->where('status', $item->key))
                    ->interval('day')
                    ->dateColumn('created_at')
                    ->between(
                        now()->subWeek(),
                        now()
                    )
                    ->count()
                    ->pluck('aggregate')
                    ->toArray(),
                'borderColor' => $item->color,
                'backgroundColor' => $item->color,
                'hoverBackgroundColor' => $item->color,
                'hoverBorderColor' => $item->color,
            ];
        }

        return [
            'datasets' => $datasets,
            'labels' => $trend->pluck('date')->toArray(),
        ];
    }

    protected function getType(): string
    {
        return 'bar';
    }
}
