<?php

namespace App\Filament\Resources;

use App\Filament\Resources\CompanyResource\Pages;
use App\Filament\Resources\CompanyResource\RelationManagers;
use App\Models\Company;
use App\Models\Country;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

class CompanyResource extends Resource
{
    protected static ?string $model = Company::class;

    protected static ?string $navigationIcon = 'heroicon-o-building-office';

    protected static ?int $navigationSort = 0;

    public static function getNavigationGroup(): ?string
    {
        return trans('ecommerce.group'); // TODO: Change the autogenerated stub
    }

    public static function getNavigationLabel(): string
    {
        return trans('ecommerce.company.title'); // TODO: Change the autogenerated stub
    }

    public static function getPluralLabel(): ?string
    {
        return trans('ecommerce.company.title');
    }

    public static function getLabel(): ?string
    {
        return trans('ecommerce.company.single'); // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make()
                    ->schema([
                        Forms\Components\SpatieMediaLibraryFileUpload::make('logo')
                            ->label(trans('ecommerce.company.columns.logo'))
                            ->collection('logo')
                            ->columnSpanFull()
                            ->image(),
                        Forms\Components\TextInput::make('name')
                            ->columnSpanFull()
                            ->label(trans('ecommerce.company.columns.name'))
                            ->required()
                            ->maxLength(255),
                        Forms\Components\TextInput::make('email')
                            ->label(trans('ecommerce.company.columns.email'))
                            ->email()
                            ->maxLength(255),
                        Forms\Components\TextInput::make('phone')
                            ->label(trans('ecommerce.company.columns.phone'))
                            ->tel()
                            ->maxLength(255),
                        Forms\Components\TextInput::make('website')
                            ->url()
                            ->label(trans('ecommerce.company.columns.website'))
                            ->maxLength(255),
                        Forms\Components\TextInput::make('ceo')
                            ->label(trans('ecommerce.company.columns.ceo'))
                            ->maxLength(255),
                        Forms\Components\TextInput::make('registration_number')
                            ->label(trans('ecommerce.company.columns.registration_number'))
                            ->maxLength(255),
                        Forms\Components\TextInput::make('tax_number')
                            ->label(trans('ecommerce.company.columns.tax_number'))
                            ->maxLength(255),
                        Forms\Components\Textarea::make('notes')
                            ->label(trans('ecommerce.company.columns.notes'))
                            ->columnSpanFull(),
                    ])->columns(2),
                Forms\Components\Section::make()
                    ->schema([
                        Forms\Components\Textarea::make('address')
                            ->columnSpanFull()
                            ->label(trans('ecommerce.company.columns.address'))
                            ->maxLength(255),
                        Forms\Components\Select::make('country_id')
                            ->searchable()
                            ->options(Country::query()->get()->pluck('name', 'id')->toArray())
                            ->label(trans('ecommerce.company.columns.country_id')),
                        Forms\Components\TextInput::make('city')
                            ->label(trans('ecommerce.company.columns.city'))
                            ->maxLength(255),
                        Forms\Components\TextInput::make('zip')
                            ->columnSpanFull()
                            ->label(trans('ecommerce.company.columns.zip'))
                            ->maxLength(255),

                    ])->columns(2),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('country.name')
                    ->label(trans('ecommerce.company.columns.country_id'))
                    ->sortable(),
                Tables\Columns\TextColumn::make('name')
                    ->label(trans('ecommerce.company.columns.name'))
                    ->sortable()
                    ->searchable(),
                Tables\Columns\TextColumn::make('email')
                    ->label(trans('ecommerce.company.columns.email'))
                    ->sortable()
                    ->searchable(),
                Tables\Columns\TextColumn::make('phone')
                    ->label(trans('ecommerce.company.columns.phone'))
                    ->sortable()
                    ->searchable(),
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            RelationManagers\CompanyBranches::class,
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListCompanies::route('/'),
            'edit' => Pages\EditCompany::route('/{record}/edit'),
        ];
    }
}
