<?php

namespace App\Filament\Resources;

use App\Filament\Resources\ShippingVendorResource\Pages;
use App\Filament\Resources\ShippingVendorResource\RelationManagers;
use App\Models\ShippingVendor;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

class ShippingVendorResource extends Resource
{
    protected static ?string $model = ShippingVendor::class;

    protected static ?string $navigationIcon = 'heroicon-o-truck';

    protected static ?int $navigationSort = 1;

    public static function getNavigationGroup(): ?string
    {
        return trans('ecommerce.group'); // TODO: Change the autogenerated stub
    }

    public static function getPluralLabel(): ?string
    {
        return trans('ecommerce.shipping.title');
    }

    public static function getNavigationLabel(): string
    {
        return trans('ecommerce.shipping.title'); // TODO: Change the autogenerated stub
    }

    public static function getLabel(): ?string
    {
        return trans('ecommerce.shipping.single'); // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\SpatieMediaLibraryFileUpload::make('logo')
                    ->label(trans('ecommerce.shipping.columns.logo'))
                    ->columnSpanFull()
                    ->collection('logo')
                    ->image(),
                Forms\Components\TextInput::make('name')
                    ->label(trans('ecommerce.shipping.columns.name'))
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('phone')
                    ->label(trans('ecommerce.shipping.columns.phone'))
                    ->tel()
                    ->maxLength(255),
                Forms\Components\Textarea::make('address')
                    ->label(trans('ecommerce.shipping.columns.address'))
                    ->columnSpanFull()
                    ->maxLength(255),
                Forms\Components\TextInput::make('contact_person')
                    ->label(trans('ecommerce.shipping.columns.contact_person'))
                    ->maxLength(255),
                Forms\Components\TextInput::make('delivery_estimation')
                    ->label(trans('ecommerce.shipping.columns.delivery_estimation'))
                    ->maxLength(255),
                Forms\Components\TextInput::make('price')
                    ->label(trans('ecommerce.shipping.columns.price'))
                    ->numeric()
                    ->columnSpanFull()
                    ->required()
                    ->default(0)
                    ->prefix('$'),
                Forms\Components\Toggle::make('is_activated')
                    ->label(trans('ecommerce.shipping.columns.is_activated')),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')
                    ->label(trans('ecommerce.shipping.columns.name'))
                    ->searchable(),
                Tables\Columns\TextColumn::make('contact_person')
                    ->label(trans('ecommerce.shipping.columns.contact_person'))
                    ->searchable(),
                Tables\Columns\TextColumn::make('delivery_estimation')
                    ->label(trans('ecommerce.shipping.columns.delivery_estimation'))
                    ->searchable(),
                Tables\Columns\TextColumn::make('phone')
                    ->label(trans('ecommerce.shipping.columns.phone'))
                    ->searchable(),
                Tables\Columns\TextColumn::make('address')
                    ->label(trans('ecommerce.shipping.columns.address'))
                    ->searchable(),
                Tables\Columns\ToggleColumn::make('is_activated')
                    ->label(trans('ecommerce.shipping.columns.is_activated')),
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            RelationManagers\ShippingDeliveryBoys::make(),
            RelationManagers\ShippingVendorPrices::make(),
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListShippingVendors::route('/'),
            'edit' => Pages\EditShippingVendor::route('/{record}/edit'),
        ];
    }
}
